### PR TITLE
New nom, better parsers

### PR DESCRIPTION
**Pull request by ghost**
using a newer nom version and used nom-derive to recreate most parsers as many of them had bugs due to expectation that the input is always valid. It passes the tests in the crate but didn't test more than what's in there.

### CODE REVIEW

**Comment by DominoTree** [comment]
Thank you so much - I'd been meaning to improve things here but I haven't had the time and I wrote this for a previous job - there are a couple things I'd like to look at to understand how they work a bit more, but this looks great!

**Comment by ghost** [comment]
You welcome, so I've done some more changes...

- formatting data record fields is optional when/if possible (good to have it like this to support PEN later)
- data records is represented by enum key and value so they can represent more things instead of using `String` only which can use alot of memory, this way we can use refs, ints, u8,..etc and can also help serialize these values differently if required
- I removed the custom json serializer and used serde instead, added some code in tests for that
- I removed BTreeMap it's very expensive for only `order` which isn't necessary except for the previous test that compares json with order but I didn't think of anyway that it can be useful so I removed it.

If you have any questions let me know, and it would be good to write more tests :)

**Comment by ghost** [comment]
I changed `parse_message` to be `-> nom::IResult` because we can parse something that is not fully ipfix, eg: something that has more bytes than an ipfix message, or whatever. Also can be used later in combination with other nom parsers for netflowv9,v5,..etc to combine them easier with `alt!'s`. 

I noticed that `parse_message` need to be rewritten but I didn't do that, this is because it accesses things using indices without checking and can cause panic with invalid/corrupt inputs. I suggest the following

```
// parses one Set and write to templates if type is Template or OptionTemplate,
// or read from templates if type is DataSet
Set::parse_one(input: &[u8], templates: &..., options_templates: &....) -> nom::IResult<&[u8], Set>


// do the same as above many times
Set::parse_many(input: &[u8], templates: &..., options_templates: &....) -> nom::IResult<&[u8], Vec<Set>> {
    .....
    named!(parse_many, many0!(complete!(Set::parse_one)));
    .....
    Ok((rest, sets))
}
// in parse_message remove loop {} and do the above in there, return the unparsed bytes at the end with the Vec<...>
```

also more tests and some benchmark for parsing. Apologies for doing major changes to the code, but I hope this is helpful for anyone.

**Comment by ghost** [comment]
- Fixed parsing FieldSpecifiers that have ident > 32767 it was due to misuse in nom-derive postexec
- Ability (to somelevel) to parse variable fields RFC7011-section-2
- Created tests from nprobe with -T "@NTOPNG@" templates to test the dns/http variable length messages

**Comment by ghost** [comment]
Added the ability to parse fields for PEN != 0, this is good for enterprise probes with custom field names..etc such as gigamon,nprobe,sonicwall,alcatel,..etc so one can define them and how they should be parsed. updated test for nprobe case with `-T "@NTOPNG@"`

**Comment by DominoTree** [comment]
Was curious why you closed this PR - did you want to do additional work and open one later? Everything so far looked fantastic.

**Pull request closed without merging**
